COMPONENT_ADD_INCLUDEDIRS += ./include
COMPONENT_ADD_INCLUDEDIRS += ../platform
COMPONENT_ADD_INCLUDEDIRS += ./source
COMPONENT_ADD_INCLUDEDIRS += ./source/st25r3911

COMPONENT_SRCDIRS += ./source/st25r3911
COMPONENT_SRCDIRS += ./source